<a href="https://colab.research.google.com/github/dmaresza/PyTorch-Course/blob/main/00_PyTorch_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7, 7)
tensor

tensor([[0.5084, 0.5541, 0.0808, 0.4501, 0.5607, 0.3831, 0.8222],
        [0.0423, 0.7627, 0.1866, 0.1645, 0.3490, 0.5206, 0.6952],
        [0.5460, 0.8112, 0.0301, 0.9291, 0.8268, 0.1045, 0.8792],
        [0.2119, 0.3043, 0.8621, 0.6551, 0.9842, 0.8853, 0.9328],
        [0.5363, 0.6343, 0.1656, 0.6819, 0.8315, 0.9111, 0.8730],
        [0.4166, 0.6817, 0.7114, 0.8226, 0.2967, 0.5561, 0.1718],
        [0.9004, 0.0824, 0.3157, 0.1923, 0.1272, 0.9603, 0.2301]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor_2 = torch.rand(1, 7)

# Perform matrix multiplication
tensor_mult = torch.mm(tensor, tensor_2.T)
tensor_mult, tensor_mult.shape

(tensor([[1.8027],
         [1.6936],
         [2.3223],
         [2.4314],
         [2.6634],
         [2.0170],
         [1.2864]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor_1 = torch.rand(7, 7)
random_tensor_2 = torch.rand(1, 7)

# Matrix multiply tensors
torch.mm(random_tensor_1, random_tensor_2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())

# Create two random tensors on GPU
gpu_tensor_1 = torch.rand(2, 3).to("cuda")
gpu_tensor_2 = torch.rand(2, 3).to("cuda")

gpu_tensor_1, gpu_tensor_2

True


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
gpu_matrix = torch.mm(gpu_tensor_1, gpu_tensor_2.T)
gpu_matrix, gpu_matrix.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(f"Max: {torch.max(gpu_matrix)}")

# Find min
print(f"Min: {torch.min(gpu_matrix)}")

Max: 0.5617256760597229
Min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(f"Max index: {torch.argmax(gpu_matrix)}")

# Find arg min
print(f"Min index: {torch.argmin(gpu_matrix)}")

Max index: 3
Min index: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and its shape as well as the second tensor and its shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed_tensor = torch.squeeze(tensor)

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(squeezed_tensor, squeezed_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
